package modele;

// Generated 3 juin 2015 11:48:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Apprenant generated by hbm2java
 */
public class Apprenant implements java.io.Serializable {

	private int numapprenant;
	private String nomapprenant;
	private String prenomapprenant;
	private Set obtients = new HashSet(0);

	public Apprenant() {
	}

	public Apprenant(int numapprenant) {
		this.numapprenant = numapprenant;
	}

	public Apprenant(int numapprenant, String nomapprenant, String prenomapprenant, Set obtients) {
		this.numapprenant = numapprenant;
		this.nomapprenant = nomapprenant;
		this.prenomapprenant = prenomapprenant;
		this.obtients = obtients;
	}

	public int getNumapprenant() {
		return this.numapprenant;
	}

	public void setNumapprenant(int numapprenant) {
		this.numapprenant = numapprenant;
	}

	public String getNomapprenant() {
		return this.nomapprenant;
	}

	public void setNomapprenant(String nomapprenant) {
		this.nomapprenant = nomapprenant;
	}

	public String getPrenomapprenant() {
		return this.prenomapprenant;
	}

	public void setPrenomapprenant(String prenomapprenant) {
		this.prenomapprenant = prenomapprenant;
	}

	public Set getObtients() {
		return this.obtients;
	}

	public void setObtients(Set obtients) {
		this.obtients = obtients;
	}

}
