package modele;

// Generated 3 juin 2015 11:48:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Objectif generated by hbm2java
 */
public class Objectif implements java.io.Serializable {

	private int numobjectif;
	private String libobectif;
	private Set actions = new HashSet(0);
	private Set missions = new HashSet(0);

	public Objectif() {
	}

	public Objectif(int numobjectif) {
		this.numobjectif = numobjectif;
	}

	public Objectif(int numobjectif, String libobectif, Set actions, Set missions) {
		this.numobjectif = numobjectif;
		this.libobectif = libobectif;
		this.actions = actions;
		this.missions = missions;
	}

	public int getNumobjectif() {
		return this.numobjectif;
	}

	public void setNumobjectif(int numobjectif) {
		this.numobjectif = numobjectif;
	}

	public String getLibobectif() {
		return this.libobectif;
	}

	public void setLibobectif(String libobectif) {
		this.libobectif = libobectif;
	}

	public Set getActions() {
		return this.actions;
	}

	public void setActions(Set actions) {
		this.actions = actions;
	}

	public Set getMissions() {
		return this.missions;
	}

	public void setMissions(Set missions) {
		this.missions = missions;
	}

}
