package com.epul.permisPiste.modele;

// Generated 3 juin 2015 11:48:35 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Calendrier generated by hbm2java
 */
public class Calendrier implements java.io.Serializable {

	private Date datejour;
	private Set obtients = new HashSet(0);

	public Calendrier() {
	}

	public Calendrier(Date datejour) {
		this.datejour = datejour;
	}

	public Calendrier(Date datejour, Set obtients) {
		this.datejour = datejour;
		this.obtients = obtients;
	}

	public Date getDatejour() {
		return this.datejour;
	}

	public void setDatejour(Date datejour) {
		this.datejour = datejour;
	}

	public Set getObtients() {
		return this.obtients;
	}

	public void setObtients(Set obtients) {
		this.obtients = obtients;
	}

}
