package com.epul.permisPiste.modele;

// Generated 3 juin 2015 11:48:35 by Hibernate Tools 4.3.1

/**
 * Obtient generated by hbm2java
 */
public class Obtient implements java.io.Serializable {

	private ObtientId id;
	private Action action;
	private Apprenant apprenant;
	private Calendrier calendrier;
	private Integer valeurdebut;
	private Integer valeurfin;

	public Obtient() {
	}

	public Obtient(ObtientId id, Action action, Apprenant apprenant, Calendrier calendrier) {
		this.id = id;
		this.action = action;
		this.apprenant = apprenant;
		this.calendrier = calendrier;
	}

	public Obtient(ObtientId id, Action action, Apprenant apprenant, Calendrier calendrier, Integer valeurdebut, Integer valeurfin) {
		this.id = id;
		this.action = action;
		this.apprenant = apprenant;
		this.calendrier = calendrier;
		this.valeurdebut = valeurdebut;
		this.valeurfin = valeurfin;
	}

	public ObtientId getId() {
		return this.id;
	}

	public void setId(ObtientId id) {
		this.id = id;
	}

	public Action getAction() {
		return this.action;
	}

	public void setAction(Action action) {
		this.action = action;
	}

	public Apprenant getApprenant() {
		return this.apprenant;
	}

	public void setApprenant(Apprenant apprenant) {
		this.apprenant = apprenant;
	}

	public Calendrier getCalendrier() {
		return this.calendrier;
	}

	public void setCalendrier(Calendrier calendrier) {
		this.calendrier = calendrier;
	}

	public Integer getValeurdebut() {
		return this.valeurdebut;
	}

	public void setValeurdebut(Integer valeurdebut) {
		this.valeurdebut = valeurdebut;
	}

	public Integer getValeurfin() {
		return this.valeurfin;
	}

	public void setValeurfin(Integer valeurfin) {
		this.valeurfin = valeurfin;
	}

}
