package com.epul.permisPiste.modele;

// Generated 3 juin 2015 11:48:35 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Regle generated by hbm2java
 */
public class Regle implements java.io.Serializable {

	private int numregle;
	private String libregle;
	private Integer scoremin;
	private Set actions = new HashSet(0);

	public Regle() {
	}

	public Regle(int numregle) {
		this.numregle = numregle;
	}

	public Regle(int numregle, String libregle, Integer scoremin, Set actions) {
		this.numregle = numregle;
		this.libregle = libregle;
		this.scoremin = scoremin;
		this.actions = actions;
	}

	public int getNumregle() {
		return this.numregle;
	}

	public void setNumregle(int numregle) {
		this.numregle = numregle;
	}

	public String getLibregle() {
		return this.libregle;
	}

	public void setLibregle(String libregle) {
		this.libregle = libregle;
	}

	public Integer getScoremin() {
		return this.scoremin;
	}

	public void setScoremin(Integer scoremin) {
		this.scoremin = scoremin;
	}

	public Set getActions() {
		return this.actions;
	}

	public void setActions(Set actions) {
		this.actions = actions;
	}

}
